### PR TITLE
plugin: don't initialize "queues" map when checking limits

### LINKED ISSUE #733: unexpected 'queue not valid for user' errors with flux accounting 0.49
In earlier versions of flux accounting, if a queue wasn't defined in the flux accounting db, any user could submit to it. After updating tioga to 0.49, users started reporting that they were getting 'queue not valid for user' errors for the default queue. I've worked around this by adding the queue to the flux accounting db and adding all of the users to it.

I was able to reproduce the issue on fluke, but it's weird. `flux account list-queues` and `view-queues` confirm that no queues are defined in the accounting db, but I get 'queue not valid for user' errors when I try to `flux run`. If I run 'flux account-priority-update', I'm able to run one job, but then subsequent jobs get the 'queue not valid for user' errors. e.g.

```
[day36@fluke1:~]$ flux run -n1 hostname
flux-run: ERROR: Queue not valid for user: batch
[day36@fluke1:~]$ sudo -u flux flux account-priority-update
[day36@fluke1:~]$ flux run -n1 hostname
flux-job: fpX9pubPLeb started                                                                                                                                                                    00:00:02
fluke126
[day36@fluke1:~]$ flux run -n1 hostname
flux-run: ERROR: Queue not valid for user: batch
[day36@fluke1:~]$
```

### PR DESCRIPTION
**Pull request by cmoussa1**
#### Problem

As mentioned in #733, when checking to see if an association is under a queue's max resources limit for a particular job, the "queues" map gets initialized with a `Queue` object unintentionally (especially if queues are not configured in the flux-accounting DB), and subsequently submitted jobs get rejected with a `"Queue not valid for user"` error message.

---

This PR reworks the `under_queue_max_resources ()` method to perform a safer lookup of the "queues" map with the passed-in queue instead of passing the queue directly in the map (which will initialize the map if the queue does not already exist). It adjusts the calls to this method to account for the change in which parameters are passed to `under_queue_max_resources ()`. I've added a simple test file to ensure that configured queues in Flux (particularly with a default queue) do not reject submitted jobs from associations when there are no queues configured in flux-accounting.

I've also added some minor cleanups to drop initialization of some of the `Association` class' queue attributes with empty strings in the case where queues are not configured in flux-accounting.

Fixes #733

### CODE REVIEW

File: src/plugins/mf_priority.cpp [hunk 1]
```diff
@@ -241,8 +241,9 @@ static int increment_resources (Association *b,
     b->cur_cores = b->cur_cores + (counts.nslots * counts.slot_size);
 
     // increment cur_nodes for queue
-    b->queue_usage[queue].cur_nodes = b->queue_usage[queue].cur_nodes +
-                                      counts.nnodes;
+    if (queue != "")
+        b->queue_usage[queue].cur_nodes = b->queue_usage[queue].cur_nodes +
+                                          counts.nnodes;
```
Comment (grondo) [inline src/plugins/mf_priority.cpp:246]: Definitely not a C++ expert, but would it be more idiomatic (and potentially a little faster) to use `!queue.empty()` here?

File: src/plugins/accounting.cpp [hunk 2]
```diff
@@ -332,11 +332,22 @@ bool Association::under_max_resources (const Job &job)
     return under_max_resources;
 }
 
-bool Association::under_queue_max_resources (const Job &job,
-                                             const Queue &queue)
+bool Association::under_queue_max_resources (
+                                    const Job &job,
+                                    const std::string &queue,
+                                    const std::map<std::string, Queue> queues)
```
Comment (grondo) [inline src/plugins/accounting.cpp:338]: Another C++ newbie question: should `queues` be passed by reference here to avoid a copy?

**Review by grondo — APPROVED** [review]
LGTM! A couple questions inline.

**Review by jameshcorbett — APPROVED** [review]
Looks reasonable!

File: src/plugins/mf_priority.cpp (hunk 1 above)
Comment (cmoussa1) [reply src/plugins/mf_priority.cpp:246]: I think you're absolutely right, thanks for this suggestion. I'll change to just use `.empty ()`.

**Comment by cmoussa1** [comment]
Thank you for the helpful feedback here @grondo and @jameshcorbett - I believe I've addressed your feedback here, so I'll go ahead and set MWP
